-- ============================================================
-- Project     : EdTech Business Analysis — SQL Portfolio
-- Database    : edtech
-- Author      : Nipun Arya
-- GitHub      : github.com/Nipunarya250
-- Description : SQL analysis covering student enrollments,
--               revenue trends, course and teacher performance,
--               and lead-to-enrollment conversion funnel.
-- ============================================================


-- ============================================================
-- SECTION 1: REVENUE ANALYSIS
-- ============================================================

-- Q1: Enrollment and Revenue Summary
-- Total enrollments, revenue, paid vs free trial split.

SELECT
    COUNT(e.enrollment_id) AS total_enrollments,
    SUM(p.amount) AS total_revenue,
    SUM(CASE WHEN e.enrollment_status = 'Paid' THEN 1 ELSE 0 END) AS total_paid,
    SUM(CASE WHEN e.enrollment_status = 'Free Trial' THEN 1 ELSE 0 END) AS total_free_trial
FROM enrollments e
LEFT JOIN payments p
    ON e.student_id = p.student_id
    AND e.course_id = p.course_id;


-- Q2: Revenue by Course Category

SELECT
    c.category,
    SUM(p.amount) AS total_category_revenue
FROM payments p
JOIN courses c ON p.course_id = c.course_id
GROUP BY c.category
ORDER BY total_category_revenue DESC;


-- Q3: Revenue by Plan Type

SELECT
    c.plan,
    SUM(p.amount) AS total_plan_revenue
FROM payments p
JOIN courses c ON p.course_id = c.course_id
GROUP BY c.plan
ORDER BY total_plan_revenue DESC;


-- Q4: Revenue by Payment Mode

SELECT
    p.payment_mode,
    SUM(p.amount) AS revenue_per_mode
FROM payments p
GROUP BY p.payment_mode
ORDER BY revenue_per_mode DESC;


-- Q5: Monthly Revenue Trend

SELECT
    YEAR(p.payment_date) AS revenue_year,
    MONTH(p.payment_date) AS revenue_month,
    SUM(p.amount) AS total_revenue
FROM payments p
GROUP BY revenue_year, revenue_month
ORDER BY revenue_year, revenue_month;


-- ============================================================
-- SECTION 2: COURSE AND TEACHER PERFORMANCE
-- ============================================================

-- Q6: Top 5 Courses by Enrollment Count

SELECT
    c.course_name,
    COUNT(e.enrollment_id) AS total_course_enrollments
FROM enrollments e
JOIN courses c ON e.course_id = c.course_id
GROUP BY c.course_name
ORDER BY total_course_enrollments DESC
LIMIT 5;


-- Q7: Top 5 Courses by Revenue

SELECT
    c.course_name,
    SUM(p.amount) AS course_revenue
FROM payments p
JOIN courses c ON p.course_id = c.course_id
GROUP BY c.course_id, c.course_name
ORDER BY course_revenue DESC
LIMIT 5;


-- Q8: Student Enrollments by Teacher

SELECT
    t.teacher_name,
    COUNT(e.enrollment_id) AS enrollment_count
FROM enrollments e
JOIN teachers t ON e.teacher_id = t.teacher_id
GROUP BY t.teacher_id, t.teacher_name
ORDER BY enrollment_count DESC;


-- Q9: Revenue Generated by Teacher

SELECT
    t.teacher_name,
    SUM(p.amount) AS revenue_per_teacher
FROM payments p
JOIN courses c ON p.course_id = c.course_id
JOIN teachers t ON c.teacher_id = t.teacher_id
GROUP BY t.teacher_id, t.teacher_name
ORDER BY revenue_per_teacher DESC;


-- ============================================================
-- SECTION 3: LEAD FUNNEL AND CAMPAIGN ANALYSIS
-- ============================================================

-- Q10: Overall Lead Conversion Rate
--
-- Two versions included to demonstrate deduplication logic.
-- Without DISTINCT: 4,664 leads | 675 converted | 14%
-- With DISTINCT:    4,519 leads | 530 converted | 12%
-- The difference confirms duplicate lead records exist in the dataset.
-- Version B (DISTINCT) is the accurate figure.

-- Version A: Without DISTINCT
WITH base AS (
    SELECT
        l.lead_id,
        e.student_id
    FROM leads l
    LEFT JOIN enrollments e
        ON l.student_id = e.student_id
        AND e.enrollment_status = 'Paid'
),
summary AS (
    SELECT
        COUNT(lead_id) AS lead_count,
        COUNT(CASE WHEN student_id IS NOT NULL THEN 1 END) AS total_converted
    FROM base
)
SELECT
    lead_count,
    total_converted,
    CONCAT(ROUND((total_converted / lead_count) * 100.0, 0), '%') AS conversion_rate
FROM summary;


-- Version B: With DISTINCT (accurate)
WITH base AS (
    SELECT DISTINCT
        l.lead_id,
        e.student_id
    FROM leads l
    LEFT JOIN enrollments e
        ON l.student_id = e.student_id
        AND e.enrollment_status = 'Paid'
),
summary AS (
    SELECT
        COUNT(lead_id) AS lead_count,
        COUNT(CASE WHEN student_id IS NOT NULL THEN 1 END) AS total_converted
    FROM base
)
SELECT
    lead_count,
    total_converted,
    CONCAT(ROUND((total_converted / lead_count) * 100.0, 0), '%') AS conversion_rate
FROM summary;


-- Q11: Conversion Rate by Campaign Source
--
-- Note: Only 4,519 leads are in the dataset after cleanup.
-- Results reflect campaign-tracked leads only.

WITH base AS (
    SELECT DISTINCT
        c.campaign_source,
        l.lead_id,
        e.student_id
    FROM campaigns c
    JOIN leads l ON c.campaign_id = l.campaign_id
    LEFT JOIN enrollments e
        ON l.student_id = e.student_id
        AND e.enrollment_status = 'Paid'
),
summary AS (
    SELECT
        campaign_source,
        COUNT(lead_id) AS lead_count,
        SUM(CASE WHEN student_id IS NOT NULL THEN 1 ELSE 0 END) AS total_converted
    FROM base
    GROUP BY campaign_source
)
SELECT
    campaign_source,
    lead_count,
    total_converted,
    CONCAT(ROUND((total_converted / lead_count) * 100, 0), '%') AS conversion_rate
FROM summary
ORDER BY conversion_rate DESC;


-- Q12: Top 5 Campaigns by Conversion Count

WITH base AS (
    SELECT DISTINCT
        c.campaign_name,
        l.lead_id,
        e.student_id
    FROM campaigns c
    JOIN leads l ON c.campaign_id = l.campaign_id
    LEFT JOIN enrollments e
        ON l.student_id = e.student_id
        AND e.enrollment_status = 'Paid'
)
SELECT
    campaign_name,
    COUNT(lead_id) AS total_leads,
    SUM(CASE WHEN student_id IS NOT NULL THEN 1 ELSE 0 END) AS total_converted,
    CONCAT(
        ROUND(
            (SUM(CASE WHEN student_id IS NOT NULL THEN 1 ELSE 0 END) / COUNT(lead_id)) * 100.0,
        0),
        '%'
    ) AS conversion_rate
FROM base
GROUP BY campaign_name
ORDER BY total_converted DESC
LIMIT 5;


-- Q13: Average Days from Lead to Paid Enrollment
--
-- Result: 81 days average after correcting swapped columns in leads table.
-- Records where lead_date > enrollment_date excluded via WHERE filter.

SELECT
    ROUND(AVG(DATEDIFF(e.enrollment_date, l.lead_date)), 1) AS avg_days_to_convert
FROM leads l
JOIN enrollments e
    ON l.student_id = e.student_id
    AND e.enrollment_status = 'Paid'
WHERE l.lead_date <= e.enrollment_date;


-- ============================================================
-- SECTION 4: WINDOW FUNCTIONS
-- ============================================================

-- Q14: Teacher Revenue Rank

WITH teacher_revenue AS (
    SELECT
        t.teacher_name,
        SUM(p.amount) AS revenue_per_teacher
    FROM payments p
    JOIN courses c ON p.course_id = c.course_id
    JOIN teachers t ON c.teacher_id = t.teacher_id
    GROUP BY t.teacher_id, t.teacher_name
)
SELECT
    teacher_name,
    revenue_per_teacher,
    RANK() OVER (ORDER BY revenue_per_teacher DESC) AS revenue_rank
FROM teacher_revenue;


-- Q15: Running Total of Monthly Revenue

WITH monthly_revenue AS (
    SELECT
        YEAR(p.payment_date) AS year_,
        MONTH(p.payment_date) AS month_,
        SUM(p.amount) AS month_total
    FROM payments p
    GROUP BY YEAR(p.payment_date), MONTH(p.payment_date)
)
SELECT
    year_,
    month_,
    month_total,
    SUM(month_total) OVER (ORDER BY year_, month_) AS running_total
FROM monthly_revenue
ORDER BY year_, month_;


-- Q16: Month-over-Month Revenue Comparison

WITH monthly_revenue AS (
    SELECT
        YEAR(p.payment_date) AS year_,
        MONTH(p.payment_date) AS month_,
        SUM(p.amount) AS revenue_of_month
    FROM payments p
    GROUP BY YEAR(p.payment_date), MONTH(p.payment_date)
)
SELECT
    year_,
    month_,
    revenue_of_month,
    LAG(revenue_of_month) OVER (ORDER BY year_, month_) AS revenue_prev_month
FROM monthly_revenue
ORDER BY year_, month_;
